---
- hosts: all
  sudo: True
  remote_user: root
  vars:
    interactive_user: vagrant
  roles:
    - postgresql-server
    - redis-server
    - erlang-dev
    - rust-dev
    - ocaml-dev
    - elixir-dev
    - zero-disk
