---
- hosts: all
  sudo: True
  remote_user: root
  vars:
    interactive_user: vagrant
    accepted_oracle_license: true
    jdk_version: 8
  roles:
    - postgresql-server
    - mongodb-server
    - redis-server
    - oracle-jdk
    - clojure-dev
    - scala-dev
    - java-dev
    - groovy-dev
    - jruby-dev
    - zero-disk
