---
- hosts: all
  sudo: True
  remote_user: root
  vars:
    interactive_user: vagrant
  roles:
    - postgresql-server
    - mongodb-server
    - redis-server
    - ruby-dev
    - nodejs-dev
    - zero-disk
