---
- hosts: all
  sudo: True
  remote_user: root
  vars:
    interactive_user: vagrant
  roles:
    - postgresql-server
    - mongodb-server
    - redis-server
    - python-dev
    - nodejs-dev
    - r-dev
    - julia-dev
    - zero-disk
